import { createSlice } from "@reduxjs/toolkit";
import { getFullPathImage } from "../../utils/ImageDetails";

export const categoriesList = [
  { name: "Home", icon: getFullPathImage("home") },
  { name: "Cities", icon: getFullPathImage("city") },
  { name: "Regions", icon: getFullPathImage("region") },
  { name: "Countries", icon: getFullPathImage("country") },
  { name: "SchoolTypes", icon: getFullPathImage("school-type"), label: "School Types" },
  { name: "Schools", icon: getFullPathImage("school"), label: "Schools" },
];

const initialState = {
  items: [],
  selected: null,
};

export const categoriesSlice = createSlice({
  name: "categories",
  initialState,
  reducers: {
    setCategories: (state, action) => {
      state.items = action.payload;
    },
    setCategory: (state, action) => {
      state.selected = action.payload;
    },
  },
});

// These 'actions' have been automatically generated by createSlice
export const { setCategories, setCategory } = categoriesSlice.actions;

export default categoriesSlice.reducer;
